<?php

/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */

//echo $block->sayHello();

//echo $block->migrateOldDataToNewTable();

?>
<div class="row clearfix">
    <div class="col-md-12 column">
        <form name="form_value" method="POST" id="form_value">
            <label>ID</label>
            <input type="text" name="id" class="form-control input-md"
            style="margin: 20px;width:300px;" autocomplete="off">
            <input type="submit" id="calculateTotalSubmit" name="calculate-total-submit"
            value="Enviar">
        </form><br><br>
        Respuesta <div class="resultconsul" style="display:none"></div>
    </div>
</div>


<script>
  require(['jquery'], function ($) {
    $(document).ready(function () {
      $(".resultconsul").hide();
      $("#form_value").submit(function () {
        var idValue = $("input[name='id']").val(); // Id a enviar
       // let url = window.location.origin + '/getdatacustomtable/index/getcustomdata';
        let url = window.location.origin + '/consulta/result/ajax';
        console.log(url);
        $.ajax({
          url: url,
          type: 'POST',
          data: {id:idValue},
          showLoader: true,
          cache: false,
          success: function (response) {
            console.log(response.output);
                    $(".resultconsul").show();
                    $(".resultconsul").text(response.output);
          }
        });
        return false;
      });
    });
  });

</script>

